baseURL = "http://localhost:1313"
languageCode = "ja-JP"
title = "My New Hugo Site"
sectionPagesMenu = "main"
canonifyurls = true
publishDir = "docs"

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.min.js"
    target = "static/js/main.js"
[menu]
    [[menu.main]]
        identifier = ""
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "cat1"
        name = "カテゴリー1"
        url = "/cat1/"
        weight = 2
    [[menu.main]]
        identifier = "cat2"
        name = "カテゴリー2"
        url = "/cat2/"
        weight = 3
    [[menu.main]]
        identifier = "page1"
        name = "ページ1"
        url = "/page1/"
        weight = 4
    [[menu.main]]
        identifier = "page2"
        name = "ページ2"
        url = "/page2/"
        weight = 5
    [[menu.main]]
        identifier = "page3"
        name = "ページ3"
        url = "/page3/"
        weight = 6